feat(print): add swappy for selected screenshots

diff --git a/bin/scripts/print b/bin/scripts/print
--- a/bin/scripts/print
+++ b/bin/scripts/print
@@ -2,16 +2,16 @@
 
 output=~/Pictures/Screenshots/$(date "+%d-%m-%Y_%H-%M-%S").png
 
-grim -g "$(slurp)" $output 
+grim -g "$(slurp)" $output && swappy -f $output 
 
 if [ $? -eq 1 ]; then
     echo "Error when attempting to screenshot the screen."
     exit 1
 fi
 
-wl-copy < $output
+# wl-copy < $output
 
-if [ $? -eq 1 ]; then
-    echo "Error when attempting to copy the screenshot to the system clipboard."
-    exit 1
-fi
+# if [ $? -eq 1 ]; then
+#     echo "Error when attempting to copy the screenshot to the system clipboard."
+#     exit 1
+# fi
